name: Build & Release

on:
  push:
    branches: [ master ]

jobs:
  # Create a GitHub release that we can add artifacts to
  Create-Release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v2
        with:
          name: Release ${{ github.ref_name }}
          draft: false
          prerelease: false
          generate_release_notes: true

  # Build the desktop release packages
  Build-Desktop:
    name: Build Desktop
    needs: Create-Release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: "adopt"
          java-version: "21"

      - name: Build project with Maven
        run: mvn -B package --file pom.xml

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            ./target/*.hpi